### ISSUE TITLE
question about Build IR

### ISSUE THREAD

**Issue by littlejlf** [pascal-lab/Tai-e#103]
### Overall Description

When using tai-e to dump IR or other analysis, I'm not very clear about how to set inputClasses, scope, and how to configure whether to analyze files reachable in the JDK; I have read the relevent docs

### Current Behavior

When using tai-e to dump IR, it shows "6709 classes with 64253 methods in the world" (I only have a few classes in the JAR file I'm analyzing), but my analysis scope is set to "App". I'm not sure why "world" involves so many classes and methods. Is it because I analyzed the JDK? However, the dumped IR in output.tir only includes classes under my appClassPath. Also, generating IR took 28 seconds, and I'm not sure if it's because unrelated classes in the "world" are affecting the speed. I only want to analyze files in the JAR or files in the JAR as well as reachable files in the JDK. How should I proceed?
![image](https://github.com/pascal-lab/Tai-e/assets/77716244/90024cd9-5f16-4152-8d82-ab1ff56780c8)
And When I use the 'reachable' option, it seems like out.tir generates many TIR files that are unrelated to the JAR I provided (unreachable control flow).
![image](https://github.com/pascal-lab/Tai-e/assets/77716244/849af956-a307-4691-817e-241361a2b5b2)
![image](https://github.com/pascal-lab/Tai-e/assets/77716244/f2a6f027-c04e-470c-801f-ed072b1b0e59)

### Expected Behavior

When scope is app,world and output only involves classes and methods which are in jar I supposed.When scope is reachable ,world and output involves classes and methods  in the JAR and reachable files in the JDK 

### Tai-e Version

Latest Version

### Tai-e Arguments

optionsFile: null
printHelp: false
classPath: []
appClassPath:
  - java-benchmarks/deadlock/code/app.jar
mainClass: deadcode.example.Test
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: true
worldCacheMode: false
scope: APP#|REACHABLE
nativeModel: true
planFile: null
analyses:
  ir-dumper: ;
onlyGenPlan: false
keepResult:
- $KEEP-ALL

### JDK Version

jdk17

### System Environment

windows 10 x64

### Additional Information

[app.zip](https://github.com/pascal-lab/Tai-e/files/15104822/app.zip)
The JAR file to be analyzed

**Comment by zhangt2333** [comment]
> but my analysis scope is set to "App". I'm not sure why "world" involves so many classes and methods.

Generally speaking, the closed world (your `6709 classes with 64253 methods in the world`) of the analyzed program is determined by the frontend of the static analyzer and related analysis options (`--input-classes`, `-cp`, `-acp`); whether to execute an analysis on the certain scope (class or method) is determined by the backend of the static analyzer and related analysis options (`-scope`).

> Also, generating IR took 28 seconds, and I'm not sure if it's because unrelated classes in the "world" are affecting the speed.

Setting the `preBuildIR` option to `false` makes IR building demand-driven, saving you time. However, it will increase the analysis time, because IR will be built during the analysis.

> And When I use the 'reachable' option, it seems like out.tir generates many TIR files that are unrelated to the JAR I provided (unreachable control flow).

Many `.tir` files that are indirectly related to the JAR you provided.

> When scope is app,world and output only involves classes and methods which are in jar I supposed.

Currently, the `output` is as you said, but the `world` is not.

As mentioned above, `world` is the entire closed world beginning from your `main` method via reference analysis during the frontend phase of the static analysis. 

No matter what the `-scope` is, the world won't change (If you feel confused by this metrics., you can output yours via `logger.info`, `world.getClassHierarchy()` and `...`.).
