### ISSUE TITLE
Does Tai-e support SootUp or has any plan to support it? 

### ISSUE THREAD

**Issue by struce2** [pascal-lab/Tai-e#27]
[SootUp home page](https://github.com/soot-oss/SootUp) 

[SootUp Introduction](https://github.com/soot-oss/SootUp/blob/develop/README.md#what-is-sootup)

[For more information](https://github.com/soot-oss/SootUp/blob/develop/README.md)

SootUp is more modern ？e.g., 
- New Improved API (without Globals/Singletons)
- Fully-Parallelizable Architecture

### Suggested solution

Fully-Parallelizable Architecture

**Comment by silverbullettt** [comment]
No. Tai-e only uses soot as a temporary front end. We are developing our own front end and will replace soot by it in the future.

**Comment by struce2** [comment]
Does this new frontend support concurrency？

**Comment by struce2** [comment]
"theWorld" is stored in a static variable, which is not supported by concurrency?

**Comment by silverbullettt** [comment]
"stored in a static variable" doesn't mean it is not supported by concurrency. We will take concurrency into account when developing new front end, e.g., building IR concurrently.

**Comment by struce2** [comment]
Sorry, I didn't make it clear, I mean whether the whole Tai-e can be concurrent, e.g., pointer analysis.

**Comment by silverbullettt** [comment]
Well, it is non-trivial to make pointer analysis concurrent (parallelization of pointer analysis can be a research topic).

(BTW, SootUp claims "Fully-Parallelizable Architecture", but it doesn't mean that all its analyses are concurrent. Analyses are components of it, not architecture.)

When we designed pointer analysis framework in Tai-e, a primary goal is extensibility, as we want to involve more developers to write analyses on top of it. That's why we compose [Analysis Plugin System](https://github.com/pascal-lab/Tai-e/wiki/Pointer-Analysis-Framework#analysis-plugin-system).

We have also considered to parallelize pointer analysis in Tai-e, but this will make it harder to write analysis plugins as the developers need to take synchronization into account. So currently we choose single-threading architecture for pointer analysis.

Tai's pointer analysis is already more efficient than the state-of-the-arts (see [our technical report](https://arxiv.org/abs/2208.00337)). If we encounter performance problems in the future, we may also consider parallelize it.

FYI, Tai-e already executes method- and class-level analyses in parallel.

**Comment by struce2** [comment]
Thanks, looking forward to the new frontend, so far soot feels a little slow. Thanks Again.

**Comment by silverbullettt** [comment]
No worries ;-)
