### ISSUE TITLE
How to specify option for whole-program analysis?

### ISSUE THREAD

**Issue by michaelphop** [pascal-lab/Tai-e#48]
If I want to analyze java ```rt.jar``` only, what setting should I put (```only-app``` ```true/false```) or modifications I need to make to the project ?
Also, I see many java excluded packages in the code (```determineExcludedPackages```)

**Comment by michaelphop** [comment]
From soot:
https://github.com/soot-oss/soot/blob/ddc7f3c6d0e68b4699ab3e23f6df36d7caea9979/src/main/java/soot/Scene.java#L198

**Comment by zhangt2333** [comment]
I guess that the [excludedPackages](https://github.com/soot-oss/soot/blob/ddc7f3c6d0e68b4699ab3e23f6df36d7caea9979/src/main/java/soot/Scene.java#L132) is used by [prepareClasses](https://github.com/soot-oss/soot/blob/ddc7f3c6d0e68b4699ab3e23f6df36d7caea9979/src/main/java/soot/Scene.java#L2037-L2039) to distinguish between app classes or lib classes in Soot.

In Tai-e, the Soot is used as a temporary frontend to generate our Tai-e IR, the analysis logic is irrelevant to Soot.

**Comment by zhangt2333** [comment]
Tai-e donot call `Scene.v().getApplicationClasses()` but `scene.getClasses()`
https://github.com/pascal-lab/Tai-e/blob/081bf63309745ae4b9406427bccb87818350c11c/src/main/java/pascal/taie/frontend/soot/SootWorldBuilder.java#L250

And the JClass's `isApplication` is affected by Soot in https://github.com/pascal-lab/Tai-e/blob/081bf63309745ae4b9406427bccb87818350c11c/src/main/java/pascal/taie/frontend/soot/SootClassBuilder.java#L107-L110

Any way, `only-app: false` will make JDK classes non-ignored so that they will be analyzed.

**Comment by michaelphop** [comment]
It seems that analyzing this takes infinite time (few days and didn't end).
Also memory consumption looks very high (~200G).
Am I missing something?

**Comment by zhangt2333** [comment]
Could you provide **a reproducible demo** so that I can easily reproduce and troubleshoot your issue ? I think you are the one who knows best how to drive it with your issue. 

I offer a example to show how to provide **a reproducible demo**: https://github.com/pascal-lab/Tai-e/commit/c5c6a0e01ca49a59a830b79fa2f4689f1691d7ca
