### ISSUE TITLE
Plan to support other languages?

### ISSUE THREAD

**Issue by SEC-fsq** [pascal-lab/Tai-e#78]
### Clear and concise description of the problem

未来考虑支持其他编程语言吗，golang、python、js等？

### Intention to submit PR

No

**Comment by zhangt2333** [comment]
Thanks for writing this issue in Chinese, it makes it very easy for a few of us developers to read. However, Tai-e is a project with an international focus, and we aim to keep our community discussions in as widely accessible a language as possible, which is English. This helps us share our open-source progress with interested individuals from all over the world. Kindly consider using English for communication in the future. We appreciate your understanding. Thank you.

---

This issue seems a bit similar to #65.

Supporting golang, python or javascript is far from trivial, and currently not part of our roadmap.

**Comment by silverbullettt** [comment]
Languages like Golang, Python, and JavaScript are significantly different from Java, and supporting them on Tai-e requires major modifications. However, we may consider supporting some Java-like or JVM-based languages in the future.
